services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    volumes:
      - type: bind
        source: ./terraform.tfvars.json
        target: /app/data.json
      - type: bind
        source: /etc/ssh/id_ssh_key.pub
        target: /tmp/docker_ssh_key.pub